<%@ Page Language="C#" MasterPageFile="MasterPage.Master" AutoEventWireup="true" CodeBehind="ViewForm.aspx.cs" Inherits="WebApplication.ViewForm" %>

<asp:Content ID="contentView" runat="server" ContentPlaceHolderID="head">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="idGridMovie" runat="server" AutoGenerateColumns="False"
        DataKeyNames="SlNo" AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True" OnRowEditing="Grid_RowEditing" OnRowCancelingEdit="Grid_RowCancelingEdit"
        OnRowDeleting="Grid_RowDeleting"
        OnRowUpdating="Grid_RowUpdating" ShowFooter="true">
        <Columns>
            <asp:TemplateField HeaderText="S.No">
                <ItemTemplate>
                    <asp:Label ID="lbSlno" runat="server" Text='<%# Bind("SlNo") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                    <asp:Button ID="btnInsert" runat="server" Text="Insert" OnClick="InsertClick"></asp:Button>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="MovieName">
                <EditItemTemplate>
                    <asp:TextBox ID="txtMovie" runat="server" Text='<%# Bind("MovieName") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbmovie" runat="server" Text='<%# Bind("MovieName") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                    <asp:TextBox ID="txtMovie" runat="server"></asp:TextBox>
                </FooterTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
