<%@ Page Language="C#" MasterPageFile="MasterPage.Master" AutoEventWireup="true" CodeBehind="ViewForm.aspx.cs" Inherits="WebApplication.ViewForm" %>

<asp:Content ID="contentView" runat="server" ContentPlaceHolderID="head">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="idGridMovie" runat="server" AutoGenerateColumns="False"   
                    DataKeyNames="id" AutoGenerateDeleteButton="True"   
                    AutoGenerateEditButton="True" onrowcancelingedit="GridView1_RowCancelingEdit"   
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing"   
                    onrowupdating="GridView1_RowUpdating">  
                    <Columns>  
                        <asp:TemplateField HeaderText="S.No">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtSlno" runat="server" Text='<%# Bind("slno") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lbSlno" runat="server" Text='<%# Bind("slno") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>  
                        <asp:TemplateField HeaderText="MovieName">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtMovie" runat="server" Text='<%# Bind("moviename") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lbmovie" runat="server" Text='<%# Bind("moviename") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>  
                    </Columns>  
        </asp:GridView>  
</asp:Content>
